# Generated by Django 3.2.12 on 2024-12-22 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_basket'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='quatity',
            new_name='quantity',
        ),
    ]
