# Generated by Django 3.2.12 on 2024-12-24 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_rename_quatity_product_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'product', 'verbose_name_plural': 'products'},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
    ]
